DROP TABLE IF EXISTS pizzas;
DROP TABLE IF EXISTS dragons;
DROP TABLE IF EXISTS potions;
DROP TABLE IF EXISTS planets;
DROP TABLE IF EXISTS blankets;

CREATE TABLE pizzas (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    toppings TEXT NOT NULL,
    sauce TEXT NOT NULL,
    price BIGINT NOT NULL
);

CREATE TABLE dragons (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    species TEXT NOT NULL,
    color TEXT NOT NULL,
    terrain TEXT NOT NULL,
    legs BIGINT NOT NULL
);

CREATE TABLE potions (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    flavor TEXT NOT NULL,
    color TEXT NOT NULL,
    price BIGINT NOT NULL
);

CREATE TABLE planets (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    color TEXT NOT NULL,
    size TEXT NOT NULL,
    rings BIGINT NOT NULL
);

CREATE TABLE blankets (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    color TEXT NOT NULL,
    size TEXT NOT NULL,
    price BIGINT NOT NULL
);